repos:
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    - id: black
      types: [python]
      language_version: python3.9 
    - id: black-jupyter
      types: [python]
      language_version: python3.9 
